// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcppK3gV5eD-2hyWhGbtdkw_1EyVbDyJQ',
    appId: '1:447770124847:android:04f758573a5204a5eadcda',
    messagingSenderId: '447770124847',
    projectId: 'ecowatt-b23eb',
    storageBucket: 'ecowatt-b23eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmSDIGotcLQDj9OVmKaIlU0JNCVBkD14',
    appId: '1:447770124847:ios:029c4c932a5dd992eadcda',
    messagingSenderId: '447770124847',
    projectId: 'ecowatt-b23eb',
    storageBucket: 'ecowatt-b23eb.firebasestorage.app',
    iosBundleId: 'com.ecowatt.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc04JIG0Iw1OeFH8anjAbDtngEsOWvqwc',
    appId: '1:447770124847:web:3e11373ce82236cfeadcda',
    messagingSenderId: '447770124847',
    projectId: 'ecowatt-b23eb',
    authDomain: 'ecowatt-b23eb.firebaseapp.com',
    storageBucket: 'ecowatt-b23eb.firebasestorage.app',
  );

}