on:
  push:
    branches:
      - main
      - release
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          check-latest: true
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - run: flutter pub get
      - run: flutter build appbundle
      - name: Push to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/**/outputs/**/*.aab"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
